### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Admexon**

### CODE REVIEW

**Comment by icodragon** [comment]
Please regenerate gentx (in the guide we set a new amount value) and do not change the amount manually, trust this CLI

**Comment by dfnodes** [comment]
Create gentx-f3bf5da96e192c3c81e66da8ed2fee2bcfb80b66.json

**Comment by kulikovae** [comment]
Add new gentx-d1600c27e1f2497c93faf56d96476518bdbf844e.json !

**Comment by Signor08** [comment]
Add new gentx-6254649e52e77917bab6dbe75a344b8eb26c48af.json

**Comment by Signor08** [comment]
validators contest gentx-kanyut.json

**Comment by Signor08** [comment]
validator contest gentx-evans.json

**Pull request closed without merging**
